export const REQUIRED_DOCS = [
  { category: "Company & Legal Documentation", name: "Product Liability Insurance Certificate" },
  { category: "Company & Legal Documentation", name: "Letter of Continuing Guarantee / Food Safety Commitment" },
  { category: "Company & Legal Documentation", name: "Ethical Code / Code of Conduct Policy" },
  { category: "Company & Legal Documentation", name: "Supplier & Manufacturing Questionnaire" },
  { category: "Food Safety Certifications", name: "BRCGS Food Safety Certificate & Audit Report" },
  { category: "Food Safety Certifications", name: "IFS Food Certificate & Audit Report" },
  { category: "Food Safety Certifications", name: "Organic Certification (if applicable)" },
  { category: "Product Technical Documents", name: "Product Specification Sheet" },
  { category: "Product Technical Documents", name: "Ingredient Statement" },
  { category: "Product Technical Documents", name: "Allergen Declaration" },
  { category: "Product Technical Documents", name: "5-Log Reduction / Pasteurization Validation" },
  { category: "Product Technical Documents", name: "Nutritional Information" },
  { category: "Quality & HACCP Documentation", name: "HACCP Plan - Juice Extraction & Concentration" },
  { category: "Quality & HACCP Documentation", name: "HACCP Plan - Fruit / Grape Processing" },
  { category: "Quality & HACCP Documentation", name: "Allergen & Cross-Contamination Program" },
  { category: "Quality & HACCP Documentation", name: "Quality Risk Assessment / Food Defense Plan" },
  { category: "Packaging & Material Compliance", name: "Food Contact Compliance Declaration" },
  { category: "Packaging & Material Compliance", name: "Packaging Migration Test Report" },
  { category: "Packaging & Material Compliance", name: "Aseptic Bag Specification" },
  { category: "Packaging & Material Compliance", name: "Drum / Packaging Stacking Compliance" },
  { category: "Regulatory & Safety Documentation", name: "Safety Data Sheet (SDS / MSDS)" },
  { category: "Regulatory & Safety Documentation", name: "Proposition 65 Statement (if applicable)" },
  { category: "Regulatory & Safety Documentation", name: "FDA / EU Food Compliance Statement" },
  { category: "Regulatory & Safety Documentation", name: "Non-GMO Declaration" },
  { category: "Logistics & Traceability", name: "Batch Coding & Labeling Example" },
  { category: "Logistics & Traceability", name: "Shipping & Transport Compliance Documents" },
  { category: "Food Safety Certifications", name: "FSSC 22000 Food Safety Certification Audit Report" },
  { category: "Food Safety Certifications", name: "SMETA / SEDEX Ethical Trade Audit Report" },
  { category: "Food Safety Certifications", name: "EU Organic Certification" },
  { category: "Food Safety Certifications", name: "USDA NOP Organic Certification" },
  { category: "Quality & HACCP Documentation", name: "OPRP Monitoring / Hazard Control Plan" },
  { category: "Quality & HACCP Documentation", name: "Food Allergen Control Program" },
  { category: "Regulatory & Safety Documentation", name: "Insurance Policy - Fire & Special Perils" },
  { category: "Regulatory & Safety Documentation", name: "US FDA Food Facility Registration" },
  { category: "Regulatory & Safety Documentation", name: "Kosher Certification" },
  { category: "Regulatory & Safety Documentation", name: "Halal Certification" },
  { category: "Regulatory & Safety Documentation", name: "SGF / IRMA Participation Confirmation" },
  { category: "Food Safety Certifications", name: "FSSC 22000 Certificate (Valid to 2027)" },
  { category: "Quality & HACCP Documentation", name: "HACCP CCP Plan Sheet" },
  { category: "Quality & HACCP Documentation", name: "Batch Coding Procedure" },
  { category: "Organic Certificate", name: "Organic Certificate" },
];
